/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckTypeRouteImport } from './routes/check/$type'
import { Route as ApiGroqTtsRouteImport } from './routes/api/groq/tts'
import { Route as ApiGroqCleanupRouteImport } from './routes/api/groq/cleanup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckTypeRoute = CheckTypeRouteImport.update({
  id: '/check/$type',
  path: '/check/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroqTtsRoute = ApiGroqTtsRouteImport.update({
  id: '/api/groq/tts',
  path: '/api/groq/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroqCleanupRoute = ApiGroqCleanupRouteImport.update({
  id: '/api/groq/cleanup',
  path: '/api/groq/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check/$type': typeof CheckTypeRoute
  '/api/groq/cleanup': typeof ApiGroqCleanupRoute
  '/api/groq/tts': typeof ApiGroqTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check/$type': typeof CheckTypeRoute
  '/api/groq/cleanup': typeof ApiGroqCleanupRoute
  '/api/groq/tts': typeof ApiGroqTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check/$type': typeof CheckTypeRoute
  '/api/groq/cleanup': typeof ApiGroqCleanupRoute
  '/api/groq/tts': typeof ApiGroqTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/check/$type' | '/api/groq/cleanup' | '/api/groq/tts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/check/$type' | '/api/groq/cleanup' | '/api/groq/tts'
  id: '__root__' | '/' | '/check/$type' | '/api/groq/cleanup' | '/api/groq/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckTypeRoute: typeof CheckTypeRoute
  ApiGroqCleanupRoute: typeof ApiGroqCleanupRoute
  ApiGroqTtsRoute: typeof ApiGroqTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check/$type': {
      id: '/check/$type'
      path: '/check/$type'
      fullPath: '/check/$type'
      preLoaderRoute: typeof CheckTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groq/tts': {
      id: '/api/groq/tts'
      path: '/api/groq/tts'
      fullPath: '/api/groq/tts'
      preLoaderRoute: typeof ApiGroqTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groq/cleanup': {
      id: '/api/groq/cleanup'
      path: '/api/groq/cleanup'
      fullPath: '/api/groq/cleanup'
      preLoaderRoute: typeof ApiGroqCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckTypeRoute: CheckTypeRoute,
  ApiGroqCleanupRoute: ApiGroqCleanupRoute,
  ApiGroqTtsRoute: ApiGroqTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
